name: AutoFilm Builder

on:
  push:
    branches:
      - main
    paths:
      - version.py

jobs:
    Docker-build:
      runs-on: ubuntu-latest
      name: Build Docker Image
      steps:
        - uses: actions/checkout@v4
    
        - name: Release version
          id: release_version
          run: |
                app_version=$(cat version.py |sed -ne "s/APP_VERSION\s=\s'v\(.*\)'/\1/gp")
                echo "app_version=$app_version" >> $GITHUB_ENV

        - name: Docker Meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ secrets.DOCKERHUB_USERNAME }}/autofilm
            tags: |
              type=raw,value=latest
              type=raw,value=${{ env.app_version }}

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
          
        - name: Build Image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            platforms: |
              linux/amd64
              linux/arm64/v8
              linux/s390x
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            cache-fom: type=gha, scope=${{ github.workflow }}-docker
            cache-to: type=gha, scope=${{ github.workflow }}-docker