name: AutoFilm-Documentary-Actions

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '请选择运行分支'
        required: true
        default: 'Dev'
  schedule:
    - cron: 0 4 25 * *

jobs:
  AutoFilm-Documentary:
    runs-on: ubuntu-latest
    steps:
    - name: 下载仓库
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: 安装Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install webdavclient3 requests

    - name: 运行AutoFilm-actions程序
      run: |
        python autofilm-actions.py --path config/documentary.config

    - name: 打包输出文件
      run: |
        zip -r AutoFilm.zip ./Meida/
      
    - name: 更新Release.md
      run: |
        echo "更新时间：$(date +'%Y年%m月%d日 %H点%M分')" >> Release.md
          
    - name: 上传到Github Action空间
      uses: actions/upload-artifact@main
      with:
        name: AutoFilm-Movie-$(date +'%Y-%m-%d')
        path: AutoFilm.zip  
      
    - name: 创建并发布Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 纪录片更新
        name: AutoFilm-纪录片
        body: TODO New Release.
        body_path: Release.md
        draft: false
        prerelease: false
        files: |
          AutoFilm.zip
          LICENSE 